[package]
name = "opaque-derive"
version = "0.1.0"
authors = ["Ben Cressey <bcressey@amazon.com>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

[lib]
proc-macro = true

[dependencies]
darling = "0.20.8"
proc-macro2 = "1.0.81"
quote = "1.0.36"
syn = "2.0.60"
