[package]
name = "opaque-settings"
version = "0.1.0"
authors = ["Ben Cressey <bcressey@amazon.com>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

[dependencies]
abi_stable = "0.11.3"
lazy_static = "1.4.0"
serde = "1.0.198"
serde_json = "1.0.116"
